//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Состав_Заказа = new HashSet<Состав_Заказа>();
        }
    
        public int id_Заказ { get; set; }
        public Nullable<System.DateTime> Дата_Доставки { get; set; }
        public Nullable<System.DateTime> Дата_Заказа { get; set; }
        public Nullable<int> Пункт_выдачи { get; set; }
        public Nullable<int> Клиент { get; set; }
        public Nullable<int> Код_для_получения { get; set; }
        public string Статус { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пункт_выдачи Пункт_выдачи1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_Заказа> Состав_Заказа { get; set; }
    }
}
