//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.Состав_Заказа = new HashSet<Состав_Заказа>();
        }
    
        public int id_Товар { get; set; }
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Ед_измерения { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public Nullable<int> Размер_макс_скидки { get; set; }
        public string Производитель { get; set; }
        public string Поставщик { get; set; }
        public Nullable<int> Категория { get; set; }
        public Nullable<int> Действущая_скидка { get; set; }
        public Nullable<int> Колличество_на_складе { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
    
        public virtual Категория Категория1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_Заказа> Состав_Заказа { get; set; }
    }
}
